name: Clone/Sync schemas

on:
  workflow_dispatch:
    inputs:
      schemas:
        description: comma seperated schema names to clone
        required: true
      uid:
        description: unique identifier for your cloned schema
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:  
    
    - name: Checkout cicd-actions
      uses: actions/checkout@v3
      with:
        repository: danone/onesource.cicd.actions
        token: ${{ secrets.ORCHESTRATION_PAT }}
        path: act
        
    - name: Dispatch to orchestration
      uses: ./act/wf-dispatcher
      with:
        owner: danone
        repo: adm.cicd.orchestration
        token: ${{ secrets.ORCHESTRATION_PAT }}
        event_type: sf-clone
        run_id: ${{ github.run_id }}
        run_attempt: ${{github.run_attempt}}
        client_payload: '{"repo": "${{ github.repository }}","schemas": "${{github.event.inputs.schemas}}","uid": "${{github.event.inputs.uid}}"}'
 
